---
- hosts: localhost
  vars:
      ansible_buffer_read_timeout: 2
  tasks:
    - name: Get Ansible Date
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Store DTG as Fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

- name: Traceroute Check
  connection: network_cli
  gather_facts: false
  hosts: switches
  tasks:
    - name: Get switch facts
      cisco.nxos.nxos_facts:
        gather_subset: all

    - name: debug
      debug:
        msg: "{{ ansible_user }}"

    - name: traceroute command
      cisco.nxos.nxos_command:
        commands:
#           - show version
          - traceroute 10.211.250.28 vrf management
      register: config

    - name: print variable
      debug:
         var: config

    - name: to find the string
      set_fact:
        tro: "{{ config|regex_search('* * *', multiline=True, ignorecase=True)}}"

    - name: print output
      debug:
         var: tro

    - name: "pick up avg value"

      debug: var=config.stdout_lines[0][9]




#
#    - name: Print output
#      debug:
#        msg: "{{ config.stdout_lines }}"
##        msg: "{{ config.stdout_lines[0][1] }}"
#
#    - name: find star index
#      ansible.builtin.command: echo {{ item }}
#      loop: "{{ config.stdout_lines|default([]) }}"
#      when: item=="* * *"


#      register: ping_output
#    - name: print output
#      debug:
#        msg: "{{ ping_output.stdout_lines }}"
#    - name: "pick up avg value"





