---
- hosts: localhost
  tasks:
    - name: Get Ansible Date
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Store DTG as Fact
      set_fact:
        DTG: "{{ ansible_date_time }}"
      register: DTG

    - name: craete variable for DTG
      set_fact: datetime={{ DTG.ansible_facts.DTG.time +'_'+ DTG.ansible_facts.DTG.date +'_'}}
    - debug: var=datetime

- name: Network Slowness Check
  connection: network_cli
  gather_facts: false
  hosts: switches

  tasks:
    - name: Get switch facts
      cisco.nxos.nxos_facts:
        gather_subset: all

    - name: debug
      debug:
        msg: "{{ ansible_user }}"

    - name: Run basic checks
      cisco.nxos.nxos_command:
        commands:
          - show version
          - show running-config
          - show ip interface brief vrf all
          - ping 10.211.250.28 vrf management
          - ping 10.211.250.62 vrf management
      register: ping_output
    - name: print output
      debug:
        msg: "{{ ping_output.stdout_lines }}"
#    - name: "pick up avg value"

#    - debug: var=ping_output.stdout_lines[0][9].split("/")[3]
#    - name: "pick up avg value"
#      set_fact: avg={{ ping_output.stdout_lines[0][9].split("/")[3] }}



#    - debug: var=ping_output.stdout_lines[0][9].split("/").strlen()

#    - debug: msg:avg[9]
#        msg: " round-trip min/avg/max {{ item.split().2 }}"
#      loop: "{{ ping_output.stdout_lines.0 }}"
#      when: item is match('^  round-trip min/avg/max(.*)$')

#    - name: ignore error
#      ansible.builtin.command: /bin/false
#      ignore_error: yes

    - name: Run basic checks
      cisco.nxos.nxos_command:
        commands:
          - traceroute 10.211.250.15 vrf management
      register: traceroute_output
    - name: print output
      debug:
       msg: "{{traceroute_output.stdout_lines}}"
- hosts: switches
  gather_facts: false

  vars:
    command_list:
          - ping 10.211.250.28 vrf management
          - ping 10.211.250.62 vrf management
          - traceroute 10.211.250.15 vrf management
  tasks:
    - name: Run the SHOW commands and save output
      cisco.nxos.nxos_command:
        commands: "{{ command_list }}"
      register: ping_traceroute_output

    - name: Put all the files together into one nice text file
      template:
        src: template.j2
        dest: "/home/labuser/ansible-playbook-logs/{{hostvars.localhost.datetime}}ping_traceroute_output.txt"

