---
- hosts: localhost

  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store Date and DTG as fact
     set_fact:
       DT: "{{ ansible_date_time.date }}"
       DTG: "{{ ansible_date_time.date +'_'+ ansible_date_time.time }}"

   - name: Create Directory with Date Name{{hostvars.localhost.DT}}
     file:
      path: /home/labuser/ansible-playbook-logs/backups/{{hostvars.localhost.DT}}
      state: directory
  run_once: true

- hosts: switches
  tasks:
   - name: Backup
     cisco.nxos.nxos_command:
       commands: show run
     register: config

   - name: print config
     debug:
       var: config

   - name: Save output to /home/labuser/ansible-playbook-logs/backups/
     copy:
       content: "{{config.stdout[0]}}"
       dest: "/home/labuser/ansible-playbook-logs/backups/{{hostvars.localhost.DT}}/{{hostvars.localhost.DTG}}-config.txt"


- hosts: localhost
  tasks:
    - name: run crone job to load data at every 30th minute of every hour
      ansible.builtin.cron:
#      become: yes
#      become_method: sudo
#      cron:
        name: "load_data"
        minute: "1"
        hour: "*"
        job: "ansible-playbook -i inventory playbook.yml"
        state: present