
---
- hosts: localhost
  tasks:
    - name: Get Ansible Date
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"

    - name: Store DTG as Fact
      set_fact:
        DTG: "{{ ansible_date_time }}"
      register: DTG

    - name: craete variable for DTG
      set_fact: datetime={{ DTG.ansible_facts.DTG.time +'_'+ DTG.ansible_facts.DTG.date +'_'}}
    - debug: var=datetime

######### Route-OFF execution on ITV-GRW-INET-RTR1A and  ITV-GRW-INET-RTR1B  #########
- name: CLI config of RTR-1A
  connection: network_cli
  gather_facts: false
  hosts: RTR1A
  tasks:
    - name: Get switch facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Route-off execution cmmand
      ios_command:
        commands:
          src: tftp://10.211.250.13//home/labuser/Ansible/ITV_akamai/RB-RTR-1A.txt
          dest: running

name: CLI config of RTR-1B
  connection: network_cli
  gather_facts: false
  hosts: RTR1B
  tasks:
    - name: Get switch facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: CLI config of RTR-1B
      ios_command:
        commands:
          src: tftp://10.211.250.13//home/labuser/Ansible/ITV_akamai/RB_RTR-1A.txt
          dest: running


name: verify routes being advertised towards Akamai
  connection: network_cli
  gather_facts: false
  hosts: RTR1A
  tasks:
    - name: Get switch facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: run show ip bgp on RTR1A
      ios_command:
        commands:
          - show ip bgp neighbor 72.52.20.97 advertised-routes
          -  show ip bgp neighbor 72.52.55.205 advertised-routes
      register: output_ip_bgp_RB_A

    - name: print running config pre check
.      debug:
        msg: "{{ output_ip_bgp_RB_A }}"

  hosts: RTR1B
  tasks:
    - name: Get switch facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: run show ip bgp on RTR1B
      ios_command:
        commands:
          - show ip bgp neighbor 72.52.20.99 advertised-routes
          - show ip bgp neighbor 72.52.55.213 advertised-routes
      register: output_ip_bgp_RB_B

    - name: print running config pre check
      debug:
        msg: "{{ output_ip_bgp_RB_B }}"

name: verify routes being advertised towards ISP 6DG
  connection: network_cli
  gather_facts: false
  hosts: RTR1A
  tasks:
    - name: Get switch facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: run show ip bgp on RTR1A
      ios_command:
        commands:
          - show ip bgp neighbor 85.92.199.145 advertised-routes

      register: output_ip_bgp_RB_A_ISP

    - name: print running config pre check
      debug:
        msg: "{{ output_ip_bgp_RB_A_ISP}}"

name: If route doesn’t propagate execute BGP soft reset out command for Akamai and 6DG neighbour
  connection: network_cli
  gather_facts: false
  hosts: RTR1A
  tasks:
    - name: Get switch facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: run show ip bgp on RTR1A
      ios_command:
        commands:
          - clear ip bgp 72.52.20.97 soft out
          - clear ip bgp 72.52.55.205 soft out
          - clear ip bgp 85.92.199.145 soft out

      register: output_ip_bgp_RB_A_Akamai_6DG

    - name: print running config pre check
      debug:
        msg: "{{ output_ip_bgp_RB_A_Akamai_6DG }}"